---
- hosts: k8s_master
  gather_facts: yes
  become: yes
  roles:
    - { role:  ../roles/kubernetes/configure-kubernetes-cluster, tags: 'configure-kubernetes-cluster' }

- hosts: k8s_master
  gather_facts: yes
  become: yes
  roles:
    - { role:  ../roles/kubernetes/configure-storage-classes, tags: 'configure-storage-classes' }