version: "3.9"
 
services:
  keycloak:


      container_name: keycloak
      image: keycloak-service:1.0.0
      build: .
      environment:
        # - KEYCLOAK_ENABLE_HEALTH_ENDPOINTS=true
        # - KEYCLOAK_ENABLE_STATISTICS=true
        # - KEYCLOAK_DATABASE_NAME=postgres
        # - KEYCLOAK_DATABASE_USER=postgres
        # - KEYCLOAK_DATABASE_PASSWORD=postgres
        # - KEYCLOAK_HOSTNAME=localhost
        # - KEYCLOAK_ADMIN=admin
        # - KEYCLOAK_ADMIN_PASSWORD=admin
        # - KEYCLOAK_DATABASE_HOST=keycloakdb
        # - KEYCLOAK_DATABASE_PORT=5432
        - KC_HEALTH_ENABLED=true
        - KC_METRICS_ENABLED=true
        - KC_DB=postgres
        - KC_DB_URL_DATABASE=postgres
        - KC_DB_URL=jdbc:postgresql://keycloakdb:5432/postgres
        - KC_HOSTNAME_ADMIN_URL=http://localhost:8080/
        - KC_HOSTNAME_URL=http://localhost:8080/
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB_URL_HOST=keycloakdb
        - KC_DB_URL_PORT=5432
        - KC_DB_USERNAME=postgres
        - KC_DB_PASSWORD=postgres
        - PROXY_ADDRESS_FORWARDING=true
        - KC_HTTP_ENABLED=true
        - KC_PROXY=edge
        - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
        - KC_PROXY_HEADERS=xforwarded
        - KC_TRANSACTION_XA_ENABLED=true
      entrypoint: "/opt/keycloak/bin/entrypoint.sh"
      ports:
        - 8080:8080
  
  keycloakdb:
    container_name: keycloakdb
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
 
    volumes:
      - keycloak_data:/var/lib/postgresql/data

volumes:
  keycloak_data: {}