---
- name: Creates ingress-controller directory
  become: yes
  become_user: kube
  file:
    path: $HOME/ingress-controller
    state: directory

- name: ingress-controller namespace
  become: yes
  become_user: kube
  template: src=./templates/ingress-controller-namespace.j2 dest=$HOME/ingress-controller/ingress-controller-namespace.yaml

- name: ingress-controller-values template
  become: yes
  become_user: kube
  template: src=./templates/ingress-controller-values.j2 dest=$HOME/ingress-controller/ingress-controller-values.yaml

- name: remove previous installation
  become: yes
  become_user: kube
  shell: |
    helm delete ingress-controller --namespace "ingress-controller-{{ lifecycle }}"
    kubectl delete -f $HOME/ingress-controller/ingress-controller-namespace.yaml
  when: ingress_controller_uninstall is defined    
  args:
    chdir: $HOME

- name: setup namespace for ingress-controller
  become: yes
  become_user: kube
  shell: |
    kubectl apply -f $HOME/ingress-controller/ingress-controller-namespace.yaml
  args:
    chdir: $HOME

- name: Deploy ingress-controller helm chart
  become: yes
  become_user: kube
  shell: |
    helm upgrade --install ingress-controller oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller -f $HOME/ingress-controller/ingress-controller-values.yaml --version "{{ nginx_ingress_controller_version }}" --namespace "ingress-controller-{{ lifecycle }}"
    exit 0
  args:
    executable: /bin/bash      
  register: SHELL_STDOUT

- name: debug output
  ansible.builtin.debug: 
    msg: "Helm Install (ingress-controller): stderr: {{ SHELL_STDOUT.stderr_lines }} stdout: {{ SHELL_STDOUT.stdout_lines }}"

- name: wait for pods to come up
  become: yes
  become_user: kube
  shell: kubectl wait --namespace="ingress-controller-{{ lifecycle }}" --for=condition=Ready pod --all 
  register: kubectl_get_pods
  until: kubectl_get_pods.stdout|split('\n')|length == ingress_controller_replicas * 2
  retries: 6
  delay: 10

- name: debug output
  ansible.builtin.debug: 
    msg: "Get pods (ingress-controller): {{ kubectl_get_pods.stdout | split('\n') }}"

- name: Delete ingress-controller directory
  become: yes
  become_user: kube
  file:
    path: $HOME/ingress-controller
    state: absent
